### ISSUE TITLE
Add the possibility to host multiple interfaces pointing to different buckets

### ISSUE THREAD

**Issue by Valgueiro** [oxyno-zeta/s3-proxy-interfaces#44]
First of all, congrats on this project, it helped me a lot!

I have a very specific case where I have multiple buckets that needs to be accessed by people that don't have access to the AWS console. I wanted to host multiple interfaces in different paths (like /bucket1, /bucket2...), but the interfaces that are here today forces the files to be on the /files path, blocking me from doing this. I would need multiple s3-proxy deployments - one for each bucket - in order to make it possible.

**Describe the solution you'd like**
I was thinking about trying to make it customizable enough so that I could have `/bucket1` interface pointing to `/bucket1/files`.

**Describe alternatives you've considered**
In the end I decided to not use interface and show the raw directory list that the s3-proxy has by default, which supports multiple buckets.

**Comment by oxyno-zeta** [comment]
Hello,

Thanks for your message :) . I'm happy to see that.

I see what you want but there isn't any support for listing targets or to have a list of path to start browsing... I can build an interface for listing targets but that will take some time.

What about creating different targets with different sites or path per bucket for the moment ?

Subpath example:
```yaml
targets:
  interface:
    mount:
      path:
        - /bucket1/
        - /bucket2/
    actions:
      GET:
        enabled: true
        config:
          indexDocument: index.html
    bucket:
      name: INTERFACE-BUCKET
      region: eu-west-1
      prefix:
  filesbucket1:
    mount:
      path:
        - /bucket1/files/
    actions:
      GET:
        enabled: true
      # Only if you want to enable upload
      PUT:
        enabled: true
      # Only if you want to enable delete
      DELETE:
        enabled: true
    bucket:
      name: BUCKET1
      region: eu-west-1
      prefix:
  filesbucket2:
    mount:
      path:
        - /bucket2/files/
    actions:
      GET:
        enabled: true
      # Only if you want to enable upload
      PUT:
        enabled: true
      # Only if you want to enable delete
      DELETE:
        enabled: true
    bucket:
      name: BUCKET2
      region: eu-west-1
      prefix:
```

Subdomain example:
```yaml
targets:
  interfacebucket1:
    mount:
      path:
        - /
      host: bucket1.DOMAIN
    actions:
      GET:
        enabled: true
        config:
          indexDocument: index.html
    bucket:
      name: INTERFACE-BUCKET
      region: eu-west-1
      prefix:
  filesbucket1:
    mount:
      path:
        - /files/
      host: bucket1.DOMAIN
    actions:
      GET:
        enabled: true
      # Only if you want to enable upload
      PUT:
        enabled: true
      # Only if you want to enable delete
      DELETE:
        enabled: true
    bucket:
      name: BUCKET1
      region: eu-west-1
      prefix:
  interfacebucket2:
    mount:
      path:
        - /
      host: bucket2.DOMAIN
    actions:
      GET:
        enabled: true
        config:
          indexDocument: index.html
    bucket:
      name: INTERFACE-BUCKET
      region: eu-west-1
      prefix:
  filesbucket2:
    mount:
      path:
        - /files/
      host: bucket2.DOMAIN
    actions:
      GET:
        enabled: true
      # Only if you want to enable upload
      PUT:
        enabled: true
      # Only if you want to enable delete
      DELETE:
        enabled: true
    bucket:
      name: BUCKET2
      region: eu-west-1
      prefix:
```

Oxyno-zeta
